"""常量定义。"""

import os

MIPEVAL_EXTRACTION_PROMPT = (
    "任务：从用户提供的输入文本中，提取指定的“application_form”结构中的信息，并严格按照 JSON 结构输出提取结果。\n"
    "\n"
    "提取目标结构（必须完全遵循此键名，不可增删或修改）：\n"
    "{\n"
    "  \"application_form\": {\n"
    "    \"unit_information\": {\n"
    "      \"unit_name\": \"string - 单位全称\",\n"
    "      \"unit_address\": \"string - 单位详细地址\",\n"
    "      \"provincial_password_authority\": \"string - 所属省部密码管理部门\",\n"
    "      \"postal_code\": \"string - 邮政编码\"\n"
    "    },\n"
    "    \"contact_information\": {\n"
    "      \"name\": \"string - 联系人姓名\",\n"
    "      \"department\": \"string - 所属部门\",\n"
    "      \"mobile_phone\": \"string - 移动电话\",\n"
    "      \"title_position\": \"string - 职务/职称\",\n"
    "      \"office_phone\": \"string - 办公电话\",\n"
    "      \"email\": \"string - 电子邮件\"\n"
    "    },\n"
    "    \"information_system\": {\n"
    "      \"system_name\": \"string - 系统名称\",\n"
    "      \"is_critical_infrastructure\": \"boolean - 是否为关键信息基础设施\",\n"
    "      \"critical_infrastructure_status\": {\n"
    "        \"identified\": \"boolean - 已认定\",\n"
    "        \"governing_department\": \"string - 所属安全保护工作部门\",\n"
    "        \"unidentified\": \"boolean - 未认定\"\n"
    "      },\n"
    "      \"classification_status\": {\n"
    "        \"has_classified\": \"boolean - 已定级备案\",\n"
    "        \"level\": \"string - 第一级（一至四），S_A_G\",\n"
    "        \"filing_certificate_number\": \"string - 备案证明编号\",\n"
    "        \"is_consistent_with_tested\": \"boolean - 本次被测信息系统与等级保护定级系统是否一致\",\n"
    "        \"change_description\": \"string - 变化情况说明\",\n"
    "        \"not_classified\": \"boolean - 未定级\",\n"
    "        \"evaluation_basis\": \"string - 本次密评依据标准\"\n"
    "      },\n"
    "      \"cybersecurity_evaluation\": {\n"
    "        \"status\": \"string - 枚举: ['已测评', '正在测评', '未测评']\",\n"
    "        \"evaluation_org_name\": \"string - 测评机构名称\",\n"
    "        \"evaluation_time\": \"string - 测评时间\",\n"
    "        \"evaluation_conclusion\": \"string - 测评结论\"\n"
    "      },\n"
    "      \"cryptography_assessment\": {\n"
    "        \"status\": \"string - 枚举: ['已评估', '正在评估', '未评估']\",\n"
    "        \"assessment_org_name\": \"string - 密评机构名称\",\n"
    "        \"assessment_time\": \"string - 评估时间\",\n"
    "        \"assessment_conclusion\": \"string - 评估结论\"\n"
    "      },\n"
    "      \"cloud_platform_dependency\": {\n"
    "        \"has_dependency\": \"boolean - 系统是否依赖不在本系统范围内的云平台运行\",\n"
    "        \"platform_name\": \"string - 云平台名称\",\n"
    "        \"platform_assessment_status\": \"string - 枚举: ['云平台已评估', '云平台正在评估', '云平台未评估']\",\n"
    "        \"assessment_org_name\": \"string - 密评机构名称\",\n"
    "        \"assessment_time\": \"string - 评估时间\",\n"
    "        \"assessment_conclusion\": \"string - 评估结论\"\n"
    "      }\n"
    "    },\n"
    "    \"assessment_agency\": {\n"
    "      \"agency_name\": \"string - 单位名称\",\n"
    "      \"agency_address\": \"string - 通信地址\",\n"
    "      \"postal_code\": \"string - 邮政编码\",\n"
    "      \"contact_person\": {\n"
    "        \"name\": \"string - 姓名\",\n"
    "        \"department\": \"string - 所属部门\",\n"
    "        \"mobile_phone\": \"string - 移动电话\",\n"
    "        \"title_position\": \"string - 职务/职称\",\n"
    "        \"office_phone\": \"string - 办公电话\",\n"
    "        \"email\": \"string - 电子邮件\"\n"
    "      },\n"
    "      \"document_metadata\": {\n"
    "        \"prepared_by\": \"string - 编制人\",\n"
    "        \"preparation_date\": \"string - 编制日期 (格式: YYYY-MM-DD)\",\n"
    "        \"reviewed_by\": \"string - 审核人\",\n"
    "        \"review_date\": \"string - 审核日期 (格式: YYYY-MM-DD)\",\n"
    "        \"approved_by\": \"string - 批准人\",\n"
    "        \"approval_date\": \"string - 批准日期 (格式: YYYY-MM-DD)\"\n"
    "      }\n"
    "    }\n"
    "  }\n"
    "}\n"
    "\n"
    "提取规则：\n"
    "1. 仅从用户输入文本中提取信息，文本中未提及的字段，统一填充为 \"未提及\"，不可自行编造。\n"
    "2. 若文本中同一字段有多个信息，需全部提取并按数组格式整理。\n"
    "3. 时间字段尽量统一为 YYYY-MM-DD，若文本中为模糊时间（如“2024年6月”“明年3月”），保留原表述。\n"
    "\n"
    "输出要求：\n"
    "1. 仅输出 JSON 格式结果，不要包含额外文字说明。\n"
    "2. 输出 JSON 必须可解析，键名不可更改。\n"
    "\n"
    "现在，请用户提供需提取信息的文本，我将按照上述结构输出 JSON。"
)

EVIDENCE_SUMMARY_PROMPT = (
    "你是一名密码应用测评专家。请阅读提供的证据原文，生成结构化的关键信息总结，供后续测评分析使用。请遵循以下要求：\n"
    "1. 结合密码应用测评步骤，概括文档中与测评对象、密码资产、管理流程、风险或问题相关的重点事实。\n"
    "2. 如原文包含规范要求、整改意见或待确认事项，请单独列出。\n"
    "3. 输出采用 Markdown 格式，包含以下小节：\n"
    "   - 基本情况概览：概述涉及的单位、系统、场景或阶段。\n"
    "   - 密评相关要点：按条目列出对测评判定有用的技术或管理信息。\n"
    "   - 风险与待办：如果未发现风险，请写“未提及”。\n"
    "4. 不要凭空编造信息，无法确认的内容标注“未提及”。\n"
)


POPPLER_PATH = os.environ.get('POPPLER_PATH', '/usr/bin')
TESSERACT_CMD = os.environ.get('TESSERACT_CMD')
API_KEY = os.environ.get('DEEPINFRA_API_KEY')

MIPEVAL_REPORT_PROMPT = (
    "请阅读并整合下述测评准备信息与证据解析结果，生成一份中文的密码应用测评报告初稿。"
    "报告应包含以下结构：\n"
    "1. 执行摘要：概述评测对象、评测目标与总体结论。\n"
    "2. 项目背景：概述被测单位与系统的基本情况、测评范围、相关准备工作的要点。\n"
    "3. 证据要点：归纳证据解析中提取的关键信息，可按主题或证据来源分组。\n"
    "4. 风险与问题：列出在资料准备或证据中发现的风险、缺陷或需跟进事项，如未检测到可说明“未发现显著风险”。\n"
    "5. 建议措施：给出针对风险或改进点的可执行建议。\n"
    "6. 结论与下一步计划：总结总体符合性，并建议下一步工作。\n"
    "\n撰写要求：\n"
    "- 使用正式、客观、易阅读的中文表述，必要时可使用列表或小标题。\n"
    "- 若某部分确实缺乏数据，请作显式说明，不要编造信息。\n"
    "- 可引用原始 JSON 中的关键字段，但应转化为自然语言。\n"
    "- 若检测到显著安全风险或准备不足，请在执行摘要和风险章节中突出。\n"
)